# Generated by Django 2.0.7 on 2018-07-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_if_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='if_fav',
            new_name='is_favorite',
        ),
    ]
